name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / haml-lint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / haml-lint (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / haml-lint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          haml_lint_config: -c ./testdata/.haml-lint.yml
          reviewdog_flags: -filter-mode=file -fail-on-error
